
-- Insert 10 sample horse listings with realistic data
INSERT INTO horse_profiles (
  user_id, horse_name, breed, sex, age, height, color, location, price, 
  disciplines, experience_level, description, pros, cons, images, 
  listing_status, is_available, trial_available, xrays_available
) VALUES 
-- 1. Premium Warmblood
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Bellissimo Z',
  'Zangersheide',
  'Gelding',
  8,
  16.3,
  'Bay',
  'Wellington, FL',
  125000,
  '{"jumping", "eventing"}',
  'advanced',
  'Exceptional 8-year-old Zangersheide gelding with proven competition record. Successfully showing in the 1.40m classes with room to move up. Beautiful movement, scopey jump, and excellent temperament. Imported from Europe with impressive bloodlines tracing to Balou du Rouet. Currently competing with amateur rider in Wellington circuit. Clean legs, no maintenance required. This is a true competitor ready for the next level.',
  '{"Proven show record", "Scopey jump", "Amateur friendly", "Clean legs", "Excellent temperament"}',
  '{"Requires experienced rider", "Can be strong in warm-up"}',
  '{"https://images.unsplash.com/photo-1452378174528-3090a4bba7b2"}',
  'published',
  true,
  true,
  true
),
-- 2. Hunter Prospect
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Royal Tribute',
  'Thoroughbred',
  'Mare',
  6,
  16.1,
  'Chestnut',
  'Lexington, KY',
  45000,
  '{"jumping", "dressage"}',
  'intermediate',
  'Gorgeous 6-year-old Thoroughbred mare with exceptional movement and jump. Perfect hunter prospect with three beautiful gaits and natural balance. Started over fences and showing great technique. Clean off-track record with no racing injuries. Currently in professional training program. Would excel in the hunter ring or as a dressage prospect. Sweet, willing personality with no vices.',
  '{"Beautiful movement", "Natural jump", "Sweet temperament", "Clean legs", "Versatile"}',
  '{"Young and still learning", "Needs consistent program"}',
  '{"https://images.unsplash.com/photo-1466721591366-2d5fba72006d"}',
  'published',
  true,
  true,
  false
),
-- 3. Schoolmaster Hunter
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Midnight Express',
  'Warmblood Cross',
  'Gelding',
  12,
  16.2,
  'Dark Bay',
  'Aiken, SC',
  65000,
  '{"jumping"}',
  'beginner',
  'Safe and reliable 12-year-old schoolmaster perfect for junior or amateur rider looking to move up the ranks. Extensive show record in 3ft hunters with multiple championship ribbons. Auto-changes, consistent distances, and forgiving of rider error. Currently teaching young rider the ropes. Up-to-date on all health care with clean pre-purchase exam. Ready to take someone to their next level.',
  '{"Schoolmaster safe", "Auto lead changes", "Consistent", "Forgiving", "Show experience"}',
  '{"Older horse", "Limited scope for higher levels"}',
  '{"https://images.unsplash.com/photo-1472396961693-142e6e269027"}',
  'published',
  true,
  false,
  true
),
-- 4. Young Prospect
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Quantum Leap',
  'Dutch Warmblood',
  'Gelding',
  4,
  16.3,
  'Grey',
  'Ocala, FL',
  35000,
  '{"jumping", "dressage"}',
  'professional',
  'Talented 4-year-old Dutch Warmblood gelding with exceptional bloodlines. Sired by a proven international show jumping stallion. Currently under saddle with beautiful gaits and natural balance. Started over small fences with excellent technique and scope. Will mature to be a true athlete for the right professional program. Located at top training facility in Ocala.',
  '{"Exceptional bloodlines", "Natural talent", "Beautiful gaits", "Athletic", "Great potential"}',
  '{"Young and green", "Needs professional program", "Time investment required"}',
  '{"https://images.unsplash.com/photo-1485833077593-4278bba3f11f"}',
  'published',
  true,  
  false,
  false
),
-- 5. Irish Sport Horse
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Killarney Gold',
  'Irish Sport Horse',
  'Mare',
  9,
  16.0,
  'Palomino',
  'Middleburg, VA',
  72000,
  '{"jumping", "eventing"}',
  'intermediate',
  'Stunning 9-year-old Irish Sport Horse mare with incredible jump and brave heart. Successfully competing in Training level eventing and 1.20m show jumping. Imported from Ireland with excellent conformation and movement. Bold cross-country horse with careful show jumping technique. Great for ambitious adult amateur or young professional. Sound and healthy with no maintenance issues.',
  '{"Bold and brave", "Careful technique", "Beautiful color", "Sound", "Versatile disciplines"}',
  '{"Can be strong cross-country", "Needs confident rider"}',
  '{"https://images.unsplash.com/photo-1493962853295-0fd70327578a"}',
  'published',
  true,
  true,
  true
),
-- 6. Hannoverian Hunter
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Weltmeister',
  'Hanoverian',
  'Gelding',
  10,
  17.0,
  'Black',
  'Wellington, FL',
  85000,
  '{"jumping", "dressage"}',
  'advanced',
  'Magnificent 10-year-old Hanoverian gelding with presence and quality that turns heads. Successfully showing in A/O hunters with multiple wins. Exceptional mover with ground-covering stride and effortless jump. Imported from Germany with premium papers. Perfect for serious competitor looking for that special horse. Currently showing with adult amateur in Wellington.',
  '{"Exceptional movement", "Show quality", "Premium bloodlines", "Proven winner", "Stunning presence"}',
  '{"Large horse needs experienced rider", "High maintenance requirements"}',
  '{"https://images.unsplash.com/photo-1452378174528-3090a4bba7b2"}',
  'published',
  true,
  true,
  true
),
-- 7. OTTB Hunter Prospect  
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Thunder Bay',
  'Thoroughbred',
  'Gelding',
  7,
  16.2,
  'Bay',
  'Tryon, NC',
  28000,
  '{"jumping"}',
  'intermediate',
  'Lovely 7-year-old OTTB gelding with excellent conformation and willing attitude. Retired sound from racing and has been retraining for sport horse career. Shows natural jumping ability and good temperament. Currently schooling 2ft6 courses with ease. Great project horse for someone looking to bring along a talented prospect. Clean legs and no behavioral issues.',
  '{"Good conformation", "Natural jumper", "Willing attitude", "Clean legs", "Affordable"}',
  '{"Still in retraining", "Needs experienced handler", "Young sport horse career"}',
  '{"https://images.unsplash.com/photo-1466721591366-2d5fba72006d"}',
  'published',
  true,
  true,
  false
),
-- 8. Oldenburg Dressage Cross
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Danzador',
  'Oldenburg',
  'Stallion',
  6,
  16.1,
  'Dapple Grey',
  'Aiken, SC',
  95000,
  '{"dressage", "jumping"}',
  'professional',
  'Exceptional 6-year-old Oldenburg stallion with FEI potential. Currently training Fourth Level dressage with scores in the 70s. Also shows talent over fences as a sport horse prospect. Imported from Germany with excellent breeding potential. Beautiful movement, correct conformation, and excellent temperament for a stallion. Suitable for breeding or competition career.',
  '{"FEI potential", "Excellent breeding", "Beautiful movement", "Dual purpose", "Proven bloodlines"}',
  '{"Stallion requires experienced handler", "Higher insurance costs", "Breeding management needed"}',
  '{"https://images.unsplash.com/photo-1472396961693-142e6e269027"}',
  'published',
  true,
  false,
  true
),
-- 9. Children's Hunter
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Peppermint Patty',
  'Welsh Cross',
  'Mare',
  14,
  15.2,
  'Chestnut',
  'Lexington, KY',
  38000,
  '{"jumping"}',
  'beginner',
  'Absolutely perfect children''s hunter with heart of gold. 14-year-old Welsh cross mare who has taught countless kids to ride and show. Consistent in the 2ft6-3ft hunters with automatic lead changes. Safe, honest, and forgiving of mistakes. Great for nervous riders or those learning to show. Up-to-date on all health care and easy keeper. A true confidence builder.',
  '{"Perfect for children", "Automatic changes", "Safe and honest", "Great teacher", "Easy keeper"}',
  '{"Older mare", "Limited scope", "Best for beginners only"}',
  '{"https://images.unsplash.com/photo-1485833077593-4278bba3f11f"}',
  'published',
  true,
  false,
  false
),
-- 10. Sport Horse Prospect
(
  (SELECT user_id FROM user_profiles LIMIT 1),
  'Cavalier King',
  'Trakehner',
  'Gelding',
  5,
  16.3,
  'Dark Brown',
  'Middleburg, VA',
  55000,
  '{"jumping", "dressage", "eventing"}',
  'intermediate',
  'Talented 5-year-old Trakehner gelding with excellent bloodlines and athletic ability. Currently showing Training Level dressage and small jumper classes. Brave, forward-thinking horse with natural balance and rhythm. Would excel in any discipline with proper training. Located at premier training facility with professional program. Great opportunity for someone looking for their next competition partner.',
  '{"Versatile athlete", "Excellent bloodlines", "Forward and brave", "Natural balance", "Professional training"}',
  '{"Young horse still developing", "Needs consistent program", "Strong forward ride"}',
  '{"https://images.unsplash.com/photo-1493962853295-0fd70327578a"}',
  'published',
  true,
  true,
  true
);
