// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yluzagrimczovtyqvxbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsdXphZ3JpbWN6b3Z0eXF2eGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjIyNjgsImV4cCI6MjA2NjAzODI2OH0.KmzuGSuJPZpfuGpdNmVv4lqLvl4I_fa8KP1UrCfRhtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);